# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
